import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import Footer from "@/components/Footer/Footer";
import { Suspense, useEffect } from "react";
import NewHeader from "@/components/Navbar/new-nav/NewHeader";
import "aos/dist/aos.css";
import AnimationAos from "@/components/ui/AnimationAos";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "leaflet/dist/leaflet.css";
import FloatingWhatsAppButton from "@/components/ui/FloatingWhatsAppButton";
import Loader from "@/components/ui/loader/Loader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-plus-jakarta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Gold Star Movers",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        data-new-gr-c-s-check-loaded="14.1248.0"
        data-gr-ext-installed=""
        className={`${geistSans.variable} ${plusJakarta.variable}`}
      >
        {/* <NavBar /> */}
        <NewHeader />
        <Suspense
          fallback={
            <Loader/>
          }
        >
          <AnimationAos>{children}</AnimationAos>
          <FloatingWhatsAppButton />
        </Suspense>
        <Footer />
      </body>
    </html>
  );
}
